@startuml

Class NodeController
{
    {method} - Setup() : void 
    {method} - Loop() : void
    {method} + Run() : void
}

Interface IMasterSlave
{
    {abstract} + Send(Address : int, Register : Node_Registers, Data : int)  : int
    {abstract} + Receive() : char[]
}

Interface INotificationOutput
{
    {abstract} + SetNotificationStyle(notificationBits : Notification) : int
    {abstract} + SetNotifictionState(state : bool) : int
}

class NotificationOutput
{
}

class SPI {
   {method} + Transfer(data: byte) : byte
}

interface IReader {
    {abstract} + CheckForCard(uid: byte[]) : bool
    {abstract} + ReadCard() : string
}

class MFRC522Reader {
    {method} + MFRC522Reader(nfc: NFCModule)
}

interface IMessageHandler {
    {abstract} + HandleReceiveMessage( Message : char[]) : Node_Registers
    {abstract} + HandleSendMessage( Data : Node_Registers) : int
}

class MessageHandler {
}

enum Node_Registers
{
    RequestForm = 0x0,
    Notifications = 0x1,
    RGB = 0x2,
    Item = 0x3,
    Active = 0x4,
    Error = 0x5
}

enum Notification
{
    Light,
    Sound,
    Vibration
}

NodeController "1" o-left- "1" INotificationOutput
NodeController "1" o-- "1" IReader
NodeController "1" o-- "1" IMessageHandler

IMessageHandler <|.. MessageHandler

MessageHandler "1" o-- "1" IMasterSlave

INotificationOutput <|.. NotificationOöutput

IMasterSlave <|.. I2C

IReader <|.. MFRC522Reader
MFRC522Reader "1" o-- "1" SPI

@enduml