@startuml

Class NodeController
{
    {method} - void Setup()
    {method} - void Loop()
    {method} + void Run()
}

Interface IMasterSlave
{
    {abstract} + void Send(int Address, Node_Registers Register, int Data)
    {abstract} + char[] Receive()
}

Interface INotificatieOutput
{
    {abstract} + bool handelNotificatie(int[] notificatieBits)
}

class NotificatieLight
{
    {method} + void write(bool state)
}
class NotificatieSound
{
    {method} + void write(bool state)
}
class NotificatieVibration
{
    {method} + void write(bool state)
}

NodeController "1" o-left- "1" INotificatieOutput
NodeController "1" o-- "1" IMasterSlave
NodeController "1" o-- "1" IReader

INotificatieOutput <|.. NotificatieLight
INotificatieOutput <|.. NotificatieSound
INotificatieOutput <|.. NotificatieVibration

IMasterSlave <|.. I2C
IMasterSlave <|.. CANBus


class SPI {
    +transfer(data: byte) : byte
}



interface IReader {
    +checkForCard(uid: byte[]) : bool
    +readCard() : string
}

class MFRC522Reader {
    +MFRC522Reader(nfc: NFCModule)
}

IReader <|.. MFRC522Reader
MFRC522Reader o-- SPI

@enduml