@startuml

Class NodeController
{
    {method} - Setup() : void 
    {method} - Loop() : void
    {method} + Run() : void
}

Interface IMasterSlave
{
    {abstract} + Send(Address : int, Register : Node_Registers, Data : int)  : void
    {abstract} + Receive() : char[]
}

Interface INotificatieOutput
{
    {abstract} + handelNotificatie(notificatieBits : int[]) : bool
}

class NotificatieLight
{
    {method} + Write(state : bool) : void
}

class NotificatieSound
{
    {method} + Write(state : bool) : void
}

class NotificatieVibration
{
    {method} + Write(state : bool) : void
}

class SPI {
   {method} + Transfer(data: byte) : byte
}

interface IReader {
    {abstract} + CheckForCard(uid: byte[]) : bool
    {abstract} + ReadCard() : string
}

class MFRC522Reader {
    {method} + MFRC522Reader(nfc: NFCModule)
}

enum Node_Registers
{
    RequestForm = 0x0,
    Notifications = 0x1,
    RGB = 0x2,
    Item = 0x3,
    Active = 0x4,
    Error = 0x5
}

NodeController "1" o-left- "1" INotificatieOutput
NodeController "1" o-- "1" IMasterSlave
NodeController "1" o-- "1" IReader

INotificatieOutput <|.. NotificatieLight
INotificatieOutput <|.. NotificatieSound
INotificatieOutput <|.. NotificatieVibration

IMasterSlave <|.. I2C
IMasterSlave <|.. CANBus

IReader <|.. MFRC522Reader
MFRC522Reader "1" o-- "1" SPI

@enduml