@startuml
Title Writer - write data
Entity MFRC522Writer
Entity NodeController
Entity SPI


MFRC522Writer -> MFRC522Writer : CheckForCard()
MFRC522Writer --> NodeController : CardAvailable
NodeController -> MFRC522Writer :  write()
MFRC522Writer -> SPI :Transfer()
SPI --> MFRC522Writer :1
MFRC522Writer --> NodeController :1

@enduml