@startuml
Title Reader - Read card
Entity MFRC522Reader
Entity NodeController
Entity MessageHandler
Entity I2C

MFRC522Reader -> MFRC522Reader : CheckForCard()
MFRC522Reader --> NodeController : CardAvailable
NodeController -> MFRC522Reader : ReadCard()
MFRC522Reader --> NodeController :String
NodeController -> MessageHandler : HandleSendMessage()
MessageHandler -> I2C: Send()
I2C --> MessageHandler: 1
MessageHandler --> NodeController: 1
@enduml
