name: Auto Assign

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened

jobs:
# Give me a job that automatically assigns NathanThus as a reviewer
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses:
          repo: kentaro-m/auto-assign-action
          ref: v1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: NathanThus
