name: Auto Assign

on:
  pull_request:
    branches:
      - main
      - development
    # types:
    #   - opened

jobs:
# Give me a job that automatically assigns NathanThus as a reviewer
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pullRequest } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.number
          });
          await github.pulls.createReviewRequest({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.number,
            reviewers: ['NathanThus']
          });