name: Auto Assign

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: peter-evans/add-reviewers@v1.2.0
      with:
        reviewers: NathanThus
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}