name: Auto Assign

on:
  pull_request:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Add assignee
        uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            github.event.pull_request.user.login

      - name: Add Nathan as reviewer
        if: github.event.pull_request.user.login != 'NathanThus'
        uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            NathanThus

      - name: Add Tom as reviewer
        if: github.event.pull_request.user.login != 'TomVer99'
        uses: wow-actions/auto-assign@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            TomVer99
